### ISSUE TITLE
위치 권한 미설정 시 앱 튕김 현상

### ISSUE THREAD

**Issue by sxxjxxhxxn** [b1g4/Application#1]
앱 설치 후 
따로 설정에서 위치 권한 부여 안하면
실행 안되고 튕기는 현상이 있습니다

log : 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.location.LocationManager.getAllProviders()' on a null object reference

**Comment by h-dyeon** [comment]
감사합니다 merged 되었습니다!
